# Generated by Django 5.2.5 on 2025-09-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0015_alter_order_items_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='return_requested',
        ),
        migrations.AddField(
            model_name='order_items',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Cancellation Requested', 'Cancellation Requested'), ('Return Requested', 'Return Requested'), ('Returned', 'Returned')], default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Refund Requested', 'Refund Requested'), ('Partially Refunded', 'Partially Refunded'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled')], default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('Not Requested', 'Not Requested'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Not Requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Cancellation Requested', 'Cancellation Requested'), ('Returned', 'Returned'), ('Return Requested', 'Return Requested')], default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Refund Requested', 'Refund Requested'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
